name: indi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2


dependencies:
  flutter: 
    sdk: flutter
  file_picker: ^10.1.9
  http: ^0.13.6
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

fonts:
  - family: TimesNewRoman
    fonts:
      - asset: assets/fonts/times_new_roman.ttf


flutter: ##dentro de esta sección puedes incluir imágenes, fuentes, etc.
  uses-material-design: true ##activa íconos y estilos de Material Design.
